#The try block does not raise any errors, so the else block is executed:
try:
  print("Hello, there")
except:
  print("Something went wrong")
else:
  print("Nothing went wrong")
